{
 "title": "Metrics",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "created_by",
    "label": "creators",
    "query": "select * from get_developers(\n    '${__from:date}',\n    '${__to:date}'\n)"
   },
   {
    "name": "commented_by",
    "label": "commenters",
    "query": "select '-' as __value, ' Not commented' as __text\nUNION\nselect name as __value, name as __text \nfrom get_developers(\n    '${__from:date}',\n    '${__to:date}'\n)"
   },
   {
    "name": "reviewed_by",
    "label": "approvers",
    "query": "select * from get_developers(\n    '${__from:date}',\n    '${__to:date}'\n)"
   },
   { "name": "merge_time_interval", "label": "Approval delay", "query": "1h,2h,5h,1d,2d,7d,100d" },
   {
    "name": "reviewer_sankey_field",
    "label": "Type",
    "query": "# comments : number_comments, # pull requests : number_pr"
   },
   {
    "name": "target_branch",
    "label": "target",
    "query": "select distinct target_branch from pull_requests\norder by target_branch"
   },
   {
    "name": "date_ref",
    "label": "Date reference",
    "query": "Completion date : completion, Creation date : creation"
   },
   {
    "name": "type",
    "label": "type",
    "query": "SELECT distinct type\nFROM pull_requests\nWHERE \n$__timeFilter(completion_date)\nORDER BY type ASC"
   },
   {
    "name": "aggregation_period",
    "query": "no aggregation : 0 day,1 week,2 weeks,1 month,3 months"
   },
   {
    "name": "repository",
    "query": "select distinct repository\nfrom pull_requests\norder by repository"
   },
   {
    "name": "percentile",
    "query": "10% : 0.1, 25% : 0.25, median : 0.5, 75% : 0.75 , 90% : 0.9"
   }
  ]
 },
 "panels": [
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 } },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 } },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 2, "w": 5, "x": 8, "y": 0 } },
  { "title": "Date reference", "type": "volkovlabs-variable-panel", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "# Pull requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n*\nFROM get_summary_statistics(\n    '${commented_by:raw}',\n    '${created_by:raw}',\n    '${reviewed_by:raw}',\n    '${target_branch:raw}',\n    '${type:raw}',\n    '${__from:date}',\n    '${__to:date}',\n    '${repository:raw}'\n)"
    }
   ]
  },
  {
   "title": "# Comments / Pull requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Comments length / Pull requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Approval speed",
   "type": "stat",
   "description": "Time between PR creation and merge (median)",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "First comment speed",
   "type": "stat",
   "description": "Time between PR creation and first comment (median)",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Changes / Pull Request",
   "type": "stat",
   "description": "Does the pull request contain too many changes?",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "type": "barchart",
   "description": "In minutes",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n*\nFROM get_summary_statistics_by_week_day(\n    '${date_ref:raw}',\n    '${commented_by:raw}',\n    '${created_by:raw}',\n    '${reviewed_by:raw}',\n    '${target_branch:raw}',\n    '${type:raw}',\n    '${__from:date}',\n    '${__to:date}',\n    '${repository:raw}'\n)"
    }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 13 }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 13 }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    { "panelId": 13 }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    { "panelId": 13 }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 13 }
   ]
  },
  {
   "title": "Aggregation period",
   "type": "volkovlabs-variable-panel",
   "description": "\"percentiles\" are calculated over \"aggregation period\"",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 12 }
  },
  {
   "title": "Percentile",
   "type": "volkovlabs-variable-panel",
   "description": "\"percentiles\" are calculated over \"aggregation period\"",
   "gridPos": { "h": 2, "w": 16, "x": 8, "y": 12 }
  },
  {
   "type": "timeseries",
   "description": "In minutes",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "select * from get_summary_statistics_by_day(\n    '${aggregation_period:raw}',\n    ${percentile},\n    '${date_ref:raw}',\n    '${commented_by:raw}',\n    '${created_by:raw}',\n    '${reviewed_by:raw}',\n    '${target_branch:raw}',\n    '${type:raw}',\n    '${__from:date}',\n    '${__to:date}',\n    '${repository:raw}'\n)"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "In minutes",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "targets": [
    { "panelId": 38 }
   ]
  },
  {
   "type": "timeseries",
   "description": "In minutes",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 38 }
   ]
  },
  {
   "type": "timeseries",
   "description": "In minutes",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    { "panelId": 38 }
   ]
  },
  {
   "type": "timeseries",
   "description": "In minutes",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    { "panelId": 38 }
   ]
  },
  {
   "type": "timeseries",
   "description": "In minutes",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "panelId": 38 }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  { "title": "Quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 22 } },
  { "type": "text", "gridPos": { "h": 2, "w": 16, "x": 8, "y": 22 } },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 23 } },
  {
   "title": "Avg # of comments / pull request",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM get_number_of_comments_by_pull_requests(\n    '${commented_by:raw}',\n    '${created_by:raw}',\n    '${reviewed_by:raw}',\n    '${target_branch:raw}',\n    '${type:raw}',\n    '${__from:date}',\n    '${__to:date}',\n    '${repository:raw}'\n)"
    }
   ]
  },
  {
   "title": "# Comments",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM get_comments_stats_by_commenters(\n    '${commented_by:raw}',\n    '${created_by:raw}',\n    '${reviewed_by:raw}',\n    '${target_branch:raw}',\n    '${type:raw}',\n    '${__from:date}',\n    '${__to:date}',\n    '${repository:raw}'\n)"
    }
   ]
  },
  {
   "title": "% of commented PR",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "# Approvals",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM get_comments_stats_by_approvers(\n    '${commented_by:raw}',\n    '${created_by:raw}',\n    '${reviewed_by:raw}',\n    '${target_branch:raw}',\n    '${type:raw}',\n    '${__from:date}',\n    '${__to:date}',\n    '${repository:raw}'\n)"
    }
   ]
  },
  {
   "title": "Comments length (total)",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Comments length (avg)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "targets": [
    { "panelId": 5 }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 42 } },
  { "title": "Distribute flow by :", "type": "volkovlabs-variable-panel", "gridPos": { "h": 2, "w": 6, "x": 8, "y": 42 } },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 43 } },
  {
   "title": "Who reviews who ?",
   "type": "volkovlabs-echarts-panel",
   "description": "Includes only commented pull requests",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM get_sankey_reviewers(\n    '${commented_by:raw}',\n    '${created_by:raw}',\n    '${reviewed_by:raw}',\n    '${target_branch:raw}',\n    '${type:raw}',\n    '${__from:date}',\n    '${__to:date}',\n    '${repository:raw}'\n) AS pr_data\n"
    }
   ]
  },
  {
   "title": "When do we review?",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM get_review_by_time_ranges(\n    '${commented_by:raw}',\n    '${created_by:raw}',\n    '${reviewed_by:raw}',\n    '${target_branch:raw}',\n    '${type:raw}',\n    '${__from:date}',\n    '${__to:date}',\n    '${repository:raw}'\n)"
    },
    {
     "rawSql": "select day_of_week_str as day from get_dates('2023-01-01', '2023-01-07')\nwhere day_of_week_str <= '6'\norder by day"
    },
    {
     "rawSql": "select time_range from get_timeranges('07:00', '20:00', 30) order by time_range"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  { "title": "Approval speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  { "title": "Merge time", "type": "volkovlabs-variable-panel", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Merge time by # changes in code",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT \n*\nFROM get_merge_time_by_complexity(\n    '${commented_by:raw}',\n    '${created_by:raw}',\n    '${reviewed_by:raw}',\n    '${target_branch:raw}',\n    '${type:raw}',\n    '${__from:date}',\n    '${__to:date}',\n    '${repository:raw}',\n    '${merge_time_interval}'\n)"
    }
   ]
  }
 ]
}