name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            src

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Check linting
        run: flake8 ./src

      - name: Check formating and imports sorting
        run: python -m isort ./src && python -m black ./src && git diff --exit-code

      - name: Check static typing
        run: mypy --namespace-packages --explicit-package-bases --check-untyped-defs ./src

  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [app, infra, domain, common, presentation]

    services:
      postgres:
        image: postgres:latest
        ports:
          - 6432:5432
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_USER: test
          DATABASE_USER_PASSWORD: test
          DATABASE_NAME: test
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests in ${{ matrix.folder }}
        run: |
          env INIT_SQL_PATH=${{ github.workspace }}/postgres/indicators.sql pytest ./src/${{ matrix.folder }}
